[5.0] KFAX-6: enhance fax_ra
2600hz/kazoo-fax pull request #14
Opened 2021-01-22 19:54 UTC by icehess

This will improve `fax_ra` in handling jobs, adds more commands and query to inspect and
remove stale workers and handles job restart.

Also fixes situation when a worker is exited abnormally and both `fax_ra` and
`fax_worker_sup` try to start the worker again.

New fax maintenance commands is added to remove or kill a worker.

### Related PRs
master: https://github.com/2600hz/kazoo-fax/pull/18

2021-01-23 09:47 UTC, lazedo commented on src/fax_ra.erl
> +
remove this, that's not how it should work

2021-01-23 09:48 UTC, lazedo commented on src/fax_ra.erl
> +            {State, {'ok', Map}};
leave history, or at least 5 last

2021-01-23 09:49 UTC, lazedo commented on src/fax_ra.erl
> +            %% removing history as it can gets very big??
remove

2021-01-23 10:00 UTC, lazedo commented on src/fax_ra.erl
> +    end;
looks the same of `force_remove_job`

2021-01-23 10:12 UTC, lazedo commented on src/fax_ra.erl
> +    %% lager:debug("starting worker for job ~s (account id: ~s)", [JobId, AccountId]),
add it back

2021-01-23 10:13 UTC, lazedo commented on src/fax_worker_sup.erl
> +-define(CHILDREN, [?WORKER_TYPE('fax_worker', 'temporary')]).
nice catch

2021-01-23 10:23 UTC, lazedo commented on src/fax_ra.erl
> +    lager:debug("recieved unknown command: ~p", [_Msg]),
`recieved`

2021-01-23 10:27 UTC, lazedo commented on src/fax_ra.erl
> +                      ),
why are you adding in individual timers ? you can set a collection at root and handle in `tick`

2021-01-23 10:30 UTC, lazedo commented on src/fax_ra.erl
> +            {State, [{'demonitor', 'process', Pid}]};
if is_worker_alive returns badrpc, why are you sending the rpc to same node ?

2021-01-23 10:32 UTC, lazedo commented on src/fax_ra.erl
> +            {NewState, {'error', 'not_found'}}
handle this in new root collection for retry and handle in `tick`

2021-01-23 10:32 UTC, lazedo commented on src/fax_ra.erl
> +            Effects = [{'timer', {'start_retry', {AccountId, JobId, Ref}}, ?START_RETRY}],
see other comments about retry / tick

2021-01-23 10:37 UTC, lazedo requested changes
see comments.
also, stale_workers should be monitored and handled in tick and not wait for someone to find that there's a staled worker

2021-01-23 16:29 UTC, icehess commented on src/fax_ra.erl
> +
ok, but anyway I saw this being used in rabbitmq.

2021-01-23 16:37 UTC, icehess commented on src/fax_ra.erl
> +    end;
not exactly, this will tries to bring down the worker process. thinking of I can merge this to `{'force_remove_job', {ForceKill, AccountId, JobId}}` and get rid of this clause.

2021-01-23 16:45 UTC, icehess commented on src/fax_ra.erl
> +                      ),
what do you mean? this starts the timers after a new leader is elected since the old timers for previous leader are canceled.

2021-01-23 16:48 UTC, icehess commented on src/fax_ra.erl
> +            {NewState, {'error', 'not_found'}}
hmm, the only concern is that if we removed/killed the job from state on propose this potentially restarts the worker again.

2021-01-23 16:56 UTC, icehess commented
@lazedo I'm not sure I understand what you asking for retry / tick. The idea of timer was to avoid rapidly restart workers slamming the system before it bring down the whole ra node or even cluster.

2021-01-24 09:57 UTC, lazedo commented on src/fax_ra.erl
>              }
these should not go into the log (process command). they should use the query. process command creates a transaction and requires agreement between servers, unlike query.

2021-02-24 18:43 UTC, icehess commented
@lazedo If you can please re-review this. Also the master version: https://github.com/2600hz/kazoo-fax/pull/18

2021-06-15 04:41 UTC, lazedo approved these changes

2021-06-15 04:42 UTC, lazedo commented
needs stress testing

2021-06-15 04:45 UTC, merged